spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping_cart
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      
server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    com.example.shopping: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
